
const polkadotApi = {

    consts: [
        'system',
        'babe',
        'timestamp',
        'indices',
        'balances',
        'transactionPayment',
        'authorship',
        'staking',
        'grandpa',
        'imOnline',
        'democracy',
        'phragmenElection',
        'treasury',
        'claims',
        'utility',
        'identity',
        'society',
        'recovery',
        'vesting',
        'scheduler',
        'proxy',
        'multisig',
        'bounties',
        'childBounties',
        'tips',
        'electionProviderMultiPhase',
        'gilt',
        'bagsList',
        'paras',
        'registrar',
        'slots',
        'auctions',
        'crowdloan'
    ],
    
    query: {
        'substrate': [
            'changesTrieConfig',
            'childStorageKeyPrefix',
            'code',
            'extrinsicIndex',
            'heapPages'
        ],
        'system': [
            'palletVersion',
            'account',
            'extrinsicCount',
            'blockWeight',
            'allExtrinsicsLen',
            'blockHash',
            'extrinsicData',
            'number',
            'parentHash',
            'digest',
            'events',
            'eventCount',
            'eventTopics',
            'lastRuntimeUpgrade',
            'upgradedToU32RefCount',
            'upgradedToTripleRefCount',
            'executionPhase'
        ],
        'babe': [
            'palletVersion',
            'epochIndex',
            'authorities',
            'genesisSlot',
            'currentSlot',
            'randomness',
            'pendingEpochConfigChange',
            'nextRandomness',
            'nextAuthorities',
            'segmentIndex',
            'underConstruction',
            'initialized',
            'authorVrfRandomness',
            'epochStart',
            'lateness',
            'epochConfig',
            'nextEpochConfig'
        ],
        'timestamp': [ 'palletVersion', 'now', 'didUpdate' ],
        'indices': [ 'palletVersion', 'accounts' ],
        'balances': [
            'palletVersion',
            'totalIssuance',
            'account',
            'locks',
            'reserves',
            'storageVersion'
        ],
        'transactionPayment': [
            'palletVersion',
            'nextFeeMultiplier',
            'storageVersion'
        ],
        'authorship': [
            'palletVersion',
            'uncles',
            'author',
            'didSetUncles'
        ],
        'staking': [
            'palletVersion',
            'historyDepth',
            'validatorCount',        
            'minimumValidatorCount',
            'invulnerables',         
            'bonded',
            'minNominatorBond',      
            'minValidatorBond',
            'minCommission',         
            'ledger',
            'payee',                 
            'validators',
            'counterForValidators',  
            'maxValidatorsCount',
            'nominators',            
            'counterForNominators',
            'maxNominatorsCount',    
            'currentEra',
            'activeEra',             
            'erasStartSessionIndex',
            'erasStakers',           
            'erasStakersClipped',
            'erasValidatorPrefs',    
            'erasValidatorReward',
            'erasRewardPoints',      
            'erasTotalStake',
            'forceEra',              
            'slashRewardFraction',
            'canceledSlashPayout',   
            'unappliedSlashes',
            'bondedEras',            
            'validatorSlashInEra',
            'nominatorSlashInEra',   
            'slashingSpans',
            'spanSlash',             
            'earliestUnappliedSlash',
            'currentPlannedSession', 
            'offendingValidators',
            'storageVersion',        
            'chillThreshold'
        ],
        'offences': [
            'palletVersion',
            'reports',
            'concurrentReportsIndex',
            'reportsByKindIndex'
        ],
        'session': [
            'palletVersion',
            'validators',
            'currentIndex',
            'queuedChanged',
            'queuedKeys',
            'disabledValidators',
            'nextKeys',
            'keyOwner'
        ],
        'grandpa': [
            'palletVersion',
            'state',
            'pendingChange',
            'nextForced',
            'stalled',
            'currentSetId',
            'setIdSession'
        ],
        'imOnline': [
            'palletVersion',
            'heartbeatAfter',
            'keys',
            'receivedHeartbeats',
            'authoredBlocks'
        ],
        'democracy': [
            'palletVersion',
            'publicPropCount',
            'publicProps',
            'depositOf',
            'preimages',
            'referendumCount',
            'lowestUnbaked',
            'referendumInfoOf',
            'votingOf',
            'lastTabledWasExternal',
            'nextExternal',
            'blacklist',
            'cancellations',
            'storageVersion'
        ],
        'council': [
            'palletVersion',
            'proposals',
            'proposalOf',
            'voting',
            'proposalCount',
            'members',
            'prime'
        ],
        'technicalCommittee': [
            'palletVersion',
            'proposals',
            'proposalOf',
            'voting',
            'proposalCount',
            'members',
            'prime'
        ],
        'phragmenElection': [
            'palletVersion',
            'members',
            'runnersUp',
            'candidates',
            'electionRounds',
            'voting'
        ],
        'technicalMembership': [
            'palletVersion', 'members', 'prime' ],
        'treasury': [
            'palletVersion', 'proposalCount', 'proposals', 'approvals' ],
        'claims': [
            'palletVersion',
            'claims',
            'total',
            'vesting',
            'signing',
            'preclaims'
        ],
        'identity': [ 'palletVersion', 'identityOf', 'superOf', 'subsOf', 'registrars' ],
        'society': [
            'palletVersion',       
            'founder',
            'rules',               
            'candidates',
            'suspendedCandidates', 
            'pot',
            'head',                
            'members',
            'suspendedMembers',    
            'bids',
            'vouching',            
            'payouts',
            'strikes',             
            'votes',
            'defender',            
            'defenderVotes',
            'maxMembers'
        ],
        'recovery': [ 'palletVersion', 'recoverable', 'activeRecoveries', 'proxy' ],
        'vesting': [ 'palletVersion', 'vesting', 'storageVersion' ],
        'scheduler': [ 'palletVersion', 'agenda', 'lookup' ],
        'proxy': [ 'palletVersion', 'proxies', 'announcements' ],
        'multisig': [ 'palletVersion', 'multisigs', 'calls' ],
        'preimage': [ 'palletVersion', 'statusFor', 'preimageFor' ],
        'bounties': [
            'palletVersion',
            'bountyCount',
            'bounties',
            'bountyDescriptions',
            'bountyApprovals'
        ],
        'childBounties': [
            'palletVersion',
            'childBountyCount',
            'parentChildBounties',
            'childBounties',
            'childBountyDescriptions',
            'childrenCuratorFees'
        ],
        tips: [ 'palletVersion', 'tips', 'reasons' ],
        electionProviderMultiPhase: [
            'palletVersion',
            'round',
            'currentPhase',
            'queuedSolution',
            'snapshot',
            'desiredTargets',
            'snapshotMetadata',
            'signedSubmissionNextIndex',
            'signedSubmissionIndices',
            'signedSubmissionsMap',
            'minimumUntrustedScore'
        ],
        gilt: [ 'palletVersion', 'queueTotals', 'queues', 'activeTotal', 'active' ],
        bagsList: [ 'palletVersion', 'listNodes', 'counterForListNodes', 'listBags' ],
        configuration: [
            'palletVersion',
            'activeConfig',
            'pendingConfigs',
            'bypassConsistencyCheck'
        ],
        parasShared: [
            'palletVersion',
            'currentSessionIndex',
            'activeValidatorIndices',
            'activeValidatorKeys'
        ],
        paraInclusion: [
            'palletVersion',
            'availabilityBitfields',
            'pendingAvailability',
            'pendingAvailabilityCommitments'
        ],
        paraInherent: [ 'palletVersion', 'included', 'onChainVotes' ],
        paraScheduler: [
            'palletVersion',
            'validatorGroups',
            'parathreadQueue',
            'availabilityCores',
            'parathreadClaimIndex',
            'sessionStartBlock',
            'scheduled'
        ],
        paras: [
            'palletVersion',
            'pvfActiveVoteMap',
            'pvfActiveVoteList',
            'parachains',
            'paraLifecycles',
            'heads',
            'currentCodeHash',
            'pastCodeHash',
            'pastCodeMeta',
            'pastCodePruning',
            'futureCodeUpgrades',
            'futureCodeHash',
            'upgradeGoAheadSignal',
            'upgradeRestrictionSignal',
            'upgradeCooldowns',
            'upcomingUpgrades',
            'actionsQueue',
            'upcomingParasGenesis',
            'codeByHashRefs',
            'codeByHash'
        ],
        initializer: [ 'palletVersion', 'hasInitialized', 'bufferedSessionChanges' ],
        dmp: [
            'palletVersion',
            'downwardMessageQueues',
            'downwardMessageQueueHeads'
        ],
        ump: [
            'palletVersion',
            'relayDispatchQueues',
            'relayDispatchQueueSize',
            'needsDispatch',
            'nextDispatchRoundStartWith',
            'overweight',
            'overweightCount'
        ],
        hrmp: [
            'palletVersion',
            'hrmpOpenChannelRequests',
            'hrmpOpenChannelRequestsList',
            'hrmpOpenChannelRequestCount',
            'hrmpAcceptedChannelRequestCount',
            'hrmpCloseChannelRequests',
            'hrmpCloseChannelRequestsList',
            'hrmpWatermarks',
            'hrmpChannels',
            'hrmpIngressChannelsIndex',
            'hrmpEgressChannelsIndex',
            'hrmpChannelContents',
            'hrmpChannelDigests'
        ],
        paraSessionInfo: [
            'palletVersion',
            'assignmentKeysUnsafe',
            'earliestStoredSession',
            'sessions'
        ],
        parasDisputes: [
            'palletVersion',
            'lastPrunedSession',
            'disputes',
            'included',
            'spamSlots',
            'frozen'
        ],
        registrar: [ 'palletVersion', 'pendingSwap', 'paras', 'nextFreeParaId' ],
        slots: [ 'palletVersion', 'leases' ],
        auctions: [
            'palletVersion',
            'auctionCounter',
            'auctionInfo',
            'reservedAmounts',
            'winning'
        ],
        crowdloan: [
            'palletVersion',
            'funds',
            'newRaise',
            'endingsCount',
            'nextFundIndex'
        ],
        xcmPallet: [
            'palletVersion',
            'queryCounter',
            'queries',
            'assetTraps',
            'safeXcmVersion',
            'supportedVersion',
            'versionNotifiers',
            'versionNotifyTargets',
            'versionDiscoveryQueue',
            'currentMigration'
        ]
    },

    rpc: {
        author: [
            'hasKey',
            'hasSessionKeys',
            'removeExtrinsic',
            'insertKey',
            'rotateKeys',
            'pendingExtrinsics',
            'submitExtrinsic',
            'submitAndWatchExtrinsic'
        ],
        babe: [ 'epochAuthorship' ],
        beefy: [ 'subscribeJustifications', 'getFinalizedHead' ],
        chain: [
            'getHeader',
            'getBlock',
            'getBlockHash',
            'getFinalizedHead',
            'subscribeNewHeads',
            'subscribeFinalizedHeads',
            'subscribeAllHeads'
        ],
        childstate: [
            'getKeys',
            'getKeysPaged',
            'getStorage',
            'getStorageEntries',
            'getStorageHash',
            'getStorageSize'
        ],
        contracts: [],
        dev: [],
        engine: [],
        net: [],
        web3: [],
        eth: [],
        grandpa: [ 
            'proveFinality', 
            'roundState', 
            'subscribeJustifications'
        ],
        mmr: [ 'generateProof' ],
        offchain: [ 'localStorageSet', 'localStorageGet' ],
        payment: [ 'queryInfo', 'queryFeeDetails' ],
        rpc: [ 'methods' ],
        state: [
            'call',
            'getKeys',
            'getPairs',
            'getKeysPaged',
            'getStorage',
            'getStorageHash',
            'getStorageSize',
            'getMetadata',
            'getRuntimeVersion',
            'queryStorage',
            'queryStorageAt',
            'getChildReadProof',
            'getReadProof',
            'subscribeRuntimeVersion',
            'subscribeStorage',
            'traceBlock',
            'trieMigrationStatus'
        ],
        syncstate: [
            'genSyncSpec'
        ],
        system: [
            'accountNextIndex',   
            'dryRun',
            'name',               
            'version',
            'chain',              
            'chainType',
            'properties',         
            'health',
            'localPeerId',        
            'localListenAddresses',
            'peers',              
            'addReservedPeer',
            'removeReservedPeer', 
            'reservedPeers',
            'nodeRoles',          
            'syncState',
            'addLogFilter',       
            'resetLogFilter'
        ],
    },
      
    events: {
        system: [
            'ExtrinsicSuccess',
            'ExtrinsicFailed',
            'CodeUpdated',
            'NewAccount',
            'KilledAccount',
            'Remarked'
        ],
        indices: [ 'IndexAssigned', 'IndexFreed', 'IndexFrozen' ],
        balances: [
            'Endowed',
            'DustLost',
            'Transfer',
            'BalanceSet',
            'Reserved',
            'Unreserved',
            'ReserveRepatriated',
            'Deposit',
            'Withdraw',
            'Slashed'
        ],
        staking: [
            'EraPaid',
            'Rewarded',
            'Slashed',
            'OldSlashingReportDiscarded',
            'StakersElected',
            'Bonded',
            'Unbonded',
            'Withdrawn',
            'Kicked',
            'StakingElectionFailed',
            'Chilled',
            'PayoutStarted',
            'ValidatorPrefsSet'
        ],
        offences: [ 'Offence' ],
        session: [ 'NewSession' ],
        grandpa: [ 'NewAuthorities', 'Paused', 'Resumed' ],
        imOnline: [ 'HeartbeatReceived', 'AllGood', 'SomeOffline' ],
        democracy: [
            'Proposed',        'Tabled',
            'ExternalTabled',  'Started',
            'Passed',          'NotPassed',
            'Cancelled',       'Executed',
            'Delegated',       'Undelegated',
            'Vetoed',          'PreimageNoted',
            'PreimageUsed',    'PreimageInvalid',
            'PreimageMissing', 'PreimageReaped',
            'Blacklisted',     'Voted',
            'Seconded'
        ],
        council: [
            'Proposed',
            'Voted',
            'Approved',
            'Disapproved',
            'Executed',
            'MemberExecuted',
            'Closed'
        ],
        technicalCommittee: [
            'Proposed',
            'Voted',
            'Approved',
            'Disapproved',
            'Executed',
            'MemberExecuted',
            'Closed'
        ],
        phragmenElection: [
            'NewTerm',
            'EmptyTerm',
            'ElectionError',
            'MemberKicked',
            'Renounced',
            'CandidateSlashed',
            'SeatHolderSlashed'
        ],
        technicalMembership: [
            'MemberAdded',
            'MemberRemoved',
            'MembersSwapped',
            'MembersReset',
            'KeyChanged',
            'Dummy'
        ],
        treasury: [
            'Proposed',
            'Spending',
            'Awarded',
            'Rejected',
            'Burnt',
            'Rollover',
            'Deposit'
        ],
        claims: [
            'Claimed'
        ],
        utility: [
            'BatchInterrupted',
            'BatchCompleted',
            'ItemCompleted',
            'DispatchedAs'
        ],
        identity: [
            'IdentitySet',
            'IdentityCleared',
            'IdentityKilled',
            'JudgementRequested',
            'JudgementUnrequested',
            'JudgementGiven',
            'RegistrarAdded',
            'SubIdentityAdded',
            'SubIdentityRemoved',
            'SubIdentityRevoked'
        ],
        society: [
            'Founded',
            'Bid',
            'Vouch',
            'AutoUnbid',
            'Unbid',
            'Unvouch',
            'Inducted',
            'SuspendedMemberJudgement',
            'CandidateSuspended',
            'MemberSuspended',
            'Challenged',
            'Vote',
            'DefenderVote',
            'NewMaxMembers',
            'Unfounded',
            'Deposit'
        ],
        recovery: [
            'RecoveryCreated',
            'RecoveryInitiated',
            'RecoveryVouched',
            'RecoveryClosed',
            'AccountRecovered',
            'RecoveryRemoved'
        ],
        vesting: [ 'VestingUpdated', 'VestingCompleted' ],
        scheduler: [ 'Scheduled', 'Canceled', 'Dispatched', 'CallLookupFailed' ],
        proxy: [
            'ProxyExecuted',
            'AnonymousCreated',
            'Announced',
            'ProxyAdded',
            'ProxyRemoved'
        ],
        multisig: [
            'NewMultisig',
            'MultisigApproval',
            'MultisigExecuted',
            'MultisigCancelled'
        ],
        preimage: [ 'Noted', 'Requested', 'Cleared' ],
        bounties: [
            'BountyProposed',
            'BountyRejected',
            'BountyBecameActive',
            'BountyAwarded',
            'BountyClaimed',
            'BountyCanceled',
            'BountyExtended'
        ],
        childBounties: [ 'Added', 'Awarded', 'Claimed', 'Canceled' ],
        tips: [ 'NewTip', 'TipClosing', 'TipClosed', 'TipRetracted', 'TipSlashed' ],
        electionProviderMultiPhase: [
            'SolutionStored',
            'ElectionFinalized',
            'Rewarded',
            'Slashed',
            'SignedPhaseStarted',
            'UnsignedPhaseStarted'
        ],
        gilt: [ 'BidPlaced', 'BidRetracted', 'GiltIssued', 'GiltThawed' ],
        bagsList: [ 'Rebagged' ],
        paraInclusion: [ 'CandidateBacked', 'CandidateIncluded', 'CandidateTimedOut' ],
        paras: [
            'CurrentCodeUpdated',
            'CurrentHeadUpdated',
            'CodeUpgradeScheduled',
            'NewHeadNoted',
            'ActionQueued',
            'PvfCheckStarted',
            'PvfCheckAccepted',
            'PvfCheckRejected'
        ],
        ump: [
            'InvalidFormat',
            'UnsupportedVersion',
            'ExecutedUpward',
            'WeightExhausted',
            'UpwardMessagesReceived',
            'OverweightEnqueued',
            'OverweightServiced'
        ],
        hrmp: [
            'OpenChannelRequested',
            'OpenChannelCanceled',
            'OpenChannelAccepted',
            'ChannelClosed'
        ],
        parasDisputes: [ 'DisputeInitiated', 'DisputeConcluded', 'DisputeTimedOut', 'Revert' ],
        registrar: [ 'Registered', 'Deregistered', 'Reserved' ],
        slots: [ 'NewLeasePeriod', 'Leased' ],
        auctions: [
            'AuctionStarted',
            'AuctionClosed',
            'Reserved',
            'Unreserved',
            'ReserveConfiscated',
            'BidAccepted',
            'WinningOffset'
        ],
        crowdloan: [
            'Created',
            'Contributed',
            'Withdrew',
            'PartiallyRefunded',
            'AllRefunded',
            'Dissolved',
            'HandleBidResult',
            'Edited',
            'MemoUpdated',
            'AddedToNewRaise'
        ],
        xcmPallet: [
            'Attempted',
            'Sent',
            'UnexpectedResponse',
            'ResponseReady',
            'Notified',
            'NotifyOverweight',
            'NotifyDispatchError',
            'NotifyDecodeFailed',
            'InvalidResponder',
            'InvalidResponderVersion',
            'ResponseTaken',
            'AssetsTrapped',
            'VersionChangeNotified',
            'SupportedVersionChanged',
            'NotifyTargetSendFail',
            'NotifyTargetMigrationFail'
        ]
    },

    rx: {
        consts: [
            'system',
            'babe',
            'timestamp',
            'indices',
            'balances',
            'transactionPayment',
            'authorship',
            'staking',
            'grandpa',
            'imOnline',
            'democracy',
            'phragmenElection',
            'treasury',
            'claims',
            'utility',
            'identity',
            'society',
            'recovery',
            'vesting',
            'scheduler',
            'proxy',
            'multisig',
            'bounties',
            'childBounties',
            'tips',
            'electionProviderMultiPhase',
            'gilt',
            'bagsList',
            'paras',
            'registrar',
            'slots',
            'auctions',
            'crowdloan'
        ],
        query: [
            'substrate',
            'system',
            'babe',
            'timestamp',
            'indices',
            'balances',
            'transactionPayment',
            'authorship',
            'staking',
            'offences',
            'session',
            'grandpa',
            'imOnline',
            'democracy',
            'council',
            'technicalCommittee',
            'phragmenElection',
            'technicalMembership',
            'treasury',
            'claims',
            'identity',
            'society',
            'recovery',
            'vesting',
            'scheduler',
            'proxy',
            'multisig',
            'preimage',
            'bounties',
            'childBounties',
            'tips',
            'electionProviderMultiPhase',
            'gilt',
            'bagsList',
            'configuration',
            'parasShared',
            'paraInclusion',
            'paraInherent',
            'paraScheduler',
            'paras',
            'initializer',
            'dmp',
            'ump',
            'hrmp',
            'paraSessionInfo',
            'parasDisputes',
            'registrar',
            'slots',
            'auctions',
            'crowdloan',
            'xcmPallet'
        ],
        tx: [
            'system',
            'babe',
            'timestamp',
            'indices',
            'balances',
            'authorship',
            'staking',
            'session',
            'grandpa',
            'imOnline',
            'democracy',
            'council',
            'technicalCommittee',
            'phragmenElection',
            'technicalMembership',
            'treasury',
            'claims',
            'utility',
            'identity',
            'society',
            'recovery',
            'vesting',
            'scheduler',
            'proxy',
            'multisig',
            'preimage',
            'bounties',
            'childBounties',
            'tips',
            'electionProviderMultiPhase',
            'gilt',
            'bagsList',
            'configuration',
            'parasShared',
            'paraInclusion',
            'paraInherent',
            'paras',
            'initializer',
            'dmp',
            'ump',
            'hrmp',
            'parasDisputes',
            'registrar',
            'slots',
            'auctions',
            'crowdloan',
            'xcmPallet'
        ],
        queryAt: [],
        registry: [],
        hasSubscriptions: [],
        rpc: [
            'author',     'babe',
            'beefy',      'chain',
            'childstate', 'contracts',
            'dev',        'engine',
            'net',        'web3',
            'eth',        'grandpa',
            'mmr',        'offchain',
            'payment',    'rpc',
            'state',      'syncstate',
            'system'
        ],
        queryMulti: [],
        runtimeVersion: [
            'initialU8aLength',
            'specName',
            'implName',
            'authoringVersion',
            'specVersion',
            'implVersion',
            'apis',
            'transactionVersion'
        ],
        extrinsicType: [],
        genesisHash: [
            '0',                '1',  '2',
            '3',                '4',  '5',
            '6',                '7',  '8',
            '9',                '10', '11',
            '12',               '13', '14',
            '15',               '16', '17',
            '18',               '19', '20',
            '21',               '22', '23',
            '24',               '25', '26',
            '27',               '28', '29',
            '30',               '31', 'registry',
            'initialU8aLength'
        ],
        derive: [
            'accounts',           'bagsList',
            'balances',           'bounties',
            'chain',              'council',
            'crowdloan',          'democracy',
            'elections',          'imOnline',
            'parachains',         'session',
            'society',            'staking',
            'technicalCommittee', 'treasury',
            'tx'
        ]
    }
}
