version: '3'
name: metaspan-io-stack

services:

  metaspan-io-www:
    container_name: metaspan-io-www
    image: docker.metaspan.io/www
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-}
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64} # see .env
    ports:
      - "${HTTP_PORT:-8081}:8080"
    environment:
      - SERVER_NAME=metaspan.io
      - API_HOST=
      - API_PORT=
      # - NUXT_PORT=8080
